modLoader="javafml"
loaderVersion="[45,)"
license="MIT"
# issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"
[[mods]]
modId="sca"
version="${file.jarVersion}"
displayName="Spontaneously Combusting Automobile"
# logoFile="sca.png"
authors="AbraXator"
displayTest="MATCH_VERSION"
description='''Lorem Ipsum'''

[[dependencies.sca]]
    modId="forge"
    mandatory=true
    versionRange="[45.0.49,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sca]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
